title: Site

tabs:
    pages:
        columns:
            left:
                width: 1/2
                sections:
                    notes:
                        type: pages
                        template:
                            - notes
                            - photography
                    photography:
            right:
                width: 1/2
    informations:
        columns:
            left:
                width: 1/3
            right:
                width: 2/3
